### ISSUE TITLE
Cannot get Slint Plugin to work

### ISSUE THREAD

**Issue by carlca** [kizeevov/slint-idea-plugin#29]
RustRover 2023.3 EAP
Build #RR-233.14015.147, built on February 7, 2024
Cargo/Rust v1.76.0

I've installed the plugin and configured the LSP setting in the settings to `/Users/carlcaulkett/.cargo/bin/slint-lsp` whereupon the Slint LSP appeared to restart successfully. Also `/Users/carlcaulkett/.cargo/bin` is in my system path.

The problem is that I can see no evidence of the plugin in use. In another issue, someone said "Occurs when I have a Slint file that compiles and runs. I hit the Show All Preview button in the gutter and I get this error, but this only happens once per session - after this nothing results."

I cannot even see where the Show All Preview is. 
Also I was hoping to get code completion suggestions but have not managed to do so!

What am I missing?

**Comment by kizeevov** [comment]
@carlca please tell me which version of slint-lsp are you using?
Does anything change if you reopen the project?

**Comment by carlca** [comment]
Thanks for the replay!
```
~/.cargo/bin
./slint-lsp --version
slint-lsp 1.4.1
```

I've just reopened the project. Nothing seems to have changed...

**Comment by kizeevov** [comment]
@carlca A new release. Please check what is fixed?

**Comment by carlca** [comment]
Hello @kizeevov! Thanks for the follow up. tbh since my initial contact, I was able to get Slit running nicely. I've just upgraded to 1.5.1 and I'm happy to report that everything still seems to be okay  😃
