### ISSUE TITLE
Consider not implementing com.intellij.platform.lsp.api.LspServerNotificationsHandler

### ISSUE THREAD

**Issue by alexander-doroshko** [kizeevov/slint-idea-plugin#40]
Hi from JetBrains!

I noticed that the plugin has `LspServerNotificationsMiddleware` class, which implements `LspServerNotificationsHandler` and replaces the native implementation of `LspServerNotificationsHandler`.

Is this because you need `showDocument()` and `applyEdit()` implementations?

Good news is that in the IDE version 2024.1, both functions are implemented natively (see [IDEA-345386](https://youtrack.jetbrains.com/issue/IDEA-345386) and [IDEA-346682](https://youtrack.jetbrains.com/issue/IDEA-346682)). The IDE version 2024.1 is already in Beta, you can give it a try.

If you need to keep plugin compatibility with older IDE versions and still have `showDocument()` and `applyEdit()` working, the best solution would be to publish two different builds of plugins with different compatibility version ranges: one with upper bound set to `233.*` and another with the lower bound set to `241`.

The plugin version for 241+ should have no custom implementation of `LspServerNotificationsHandler` at all. Hopefully, the native implementation works fine. If not, please file an [issue](https://youtrack.jetbrains.com/issues?q=project:%20IDEA%20subsystem:%20%7BCore.%20LSP%7D%20) (`project: IDEA, Subsystem: {Core. LSP}`)

The plugin version for older IDE versions may contain `LspServerNotificationsMiddleware`, but I'd recommend reverting [this commit](https://github.com/kizeevov/slint-idea-plugin/commit/9f0f9f0da45fa43b42f69e5b0138e45fdfd1c05e). This commit effectively removes all the internal logic that the IntelliJ Platform has. The plugin may get missing or broken functionality by not having the proper implementation of `publishDiagnostics`, `registerCapability`, and other functions.

By the way, feel free to ask any LSP API-related questions in the `#intellij-platform` channel in the [JetBrains Platform Slack](https://plugins.jetbrains.com/slack/).

**Comment by alexander-doroshko** [comment]
> But the showDocument() method is not working as expected yet.

Do you mean that `ShowDocumentParams.selection` is not respected or something else?

**Comment by kizeevov** [comment]
Yes. But I'm not sure if the API is the problem. Maybe I'm doing something wrong. I want to explore this problem more.

**Comment by alexander-doroshko** [comment]
Indeed, `ShowDocumentParams.selection` is not respected. I'll fix it in 2024.1.1. The rest should just work. Let me know if it doesn't.

**Comment by kizeevov** [comment]
Thank you very much! The rest really works well.
