### ISSUE TITLE
Rustrover cannot use this plugin

### ISSUE THREAD

**Issue by LeeeSe** [kizeevov/slint-idea-plugin#5]
Plugin 'Slint' (version '0.1.4') is not compatible with the current version of the IDE as it requires internal version number 232.* or older, but the current internal version number is RR-233.8264.32

**Comment by LeeeSe** [comment]
As far as I know, rustrover has already opened the lsp api to developers

**Comment by kizeevov** [comment]
Yes, that's right. Rustrover supports the lsp api in new versions. I was focused on finalizing the plugin and didn't publish new versions. In the coming days I will post a version with preview support and Rustrover support.

**Comment by LeeeSe** [comment]
Thank you for your excellent work!

**Comment by kizeevov** [comment]
Yes, thank you! I found more grammar problems 😕. 
I couldn't write a lexer without a grammar parser. Because of this, it is necessary to maintain the slint grammar separately. Please create an issues if you find more problems or if you need additional features
