### ISSUE TITLE
There is preview support?

### ISSUE THREAD

**Issue by maxenko** [kizeevov/slint-idea-plugin#51]
How does one activate it?

**Comment by kizeevov** [comment]
Yes, there is preview support. Click on the icon next to the component definition. 
<img width="655" alt="image" src="https://github.com/kizeevov/slint-idea-plugin/assets/29508723/cdcc4b85-4a62-4c23-9913-b7d4598ec412">

**Comment by maxenko** [comment]
Thank you, I was looking in menus!
