### ISSUE TITLE
Able to See Properties?

### ISSUE THREAD

**Issue by Joshua-Leisman** [kizeevov/slint-idea-plugin#58]
Q/A about if it is possible to see the properties of a widget using this plugin. I know that the VS extension shows a pane with all the possible properties and wondering if this extension can do the same?

**Comment by kizeevov** [comment]
There were no plans to make a property viewer on the IDEA side in the near future. But soon there will be support for the new version of [Slint 1.7 Released](https://slint.dev/blog/slint-1.7-released).
You can try it now using an external lsp server version 1.7 ([see details](https://github.com/kizeevov/slint-idea-plugin?tab=readme-ov-file#dependencies))

**Comment by bart-sensirion-qm** [comment]
Do you mean that you will only support the new version of the DSL (.slint files) or also update the live preview included in the plugin?

**Comment by kizeevov** [comment]
At the moment, I will update the live preview included in the plugin.  Many features from the new DSL version should work. 
The plug-in's current functionality is enough for my project. But, create an issues if you have any ideas on new features or problems.

**Comment by Joshua-Leisman** [comment]
The preview view of Slint allows for toggling between interact and edit. Thank you @kizeevov
